# Generated by Django 3.2.4 on 2023-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workout_name', models.CharField(max_length=100)),
                ('Muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Legs', 'Legs'), ('Shoulder', 'Shoulder'), ('Back', 'Back'), ('Abs', 'Abs'), ('Cardio', 'Cardio')], max_length=100)),
                ('Rep1', models.IntegerField(default=0)),
                ('Weight1', models.IntegerField(default=0)),
                ('Rep2', models.IntegerField(default=0)),
                ('Weight2', models.IntegerField(default=0)),
                ('Rep3', models.IntegerField(default=0)),
                ('Weight3', models.IntegerField(default=0)),
                ('Workout', models.ManyToManyField(related_name='workout_cat', to='Workouts.Workout')),
            ],
        ),
    ]
