# Generated by Django 3.2.4 on 2023-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Time',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='workcount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
